// <auto-generated />
namespace Practice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitNewTTT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitNewTTT));
        
        string IMigrationMetadata.Id
        {
            get { return "202403021720230_InitNewTTT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
